### ISSUE TITLE
The code couldn't be compiled successfully.

### ISSUE THREAD

**Issue by Starter001** [zeek/zeek-3rdparty#1]
Compiled environment:
ubuntu 12.04
gcc-4.8 g++-4.8
cmake version 3.11.3

When try to execute the make command in the build directory, it show up the following errors:
are there someone meet this issue and give me some help. Thanks! 

In file included from 
/home/opensource/zeek-master/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:45:33: error: policy_type is not a class, namespace, or enumeration
   using deficit_type = typename policy_type::deficit_type;
                                 ^
/home/opensource/zeek-master/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:64:3: error: deficit_type does not name a type
   deficit_type deficit() const {
   ^
/home/opensource/zeek-master/aux/broker/3rdparty/caf/libcaf_core/caf/intrusive/drr_queue.hpp:77:20: error: deficit_type has not been declared
   void inc_deficit(deficit_type x) noexcept {

**Comment by jsiwek** [comment]
GCC >= 4.8.3 is required to compile CAF (https://github.com/actor-framework/actor-framework).
